### PR TITLE
Added Program to Check for Armstrong Number

### PR DESCRIPTION
**Pull request by accodes21**
Program to Check for Armstrong number of n digits using while loop.
Code follows the code of conduct and has no conflict.

### CODE REVIEW

**Comment by adarsh-gupta101** [comment]
Congrats on the merge😍🚀

**Comment by accodes21** [comment]
Thank you very much Adarsh Bhai.
You are doing great work as a maintainer!💯

**Comment by adarsh-gupta101** [comment]
I hope so, while I was  reviewing the code, I found you haven't created it as a function can you do the same and raise again?

**Comment by adarsh-gupta101** [comment]
for example


function armNum(){
}

instead of console logging, return the result

**Comment by accodes21** [comment]
Oh yup i saw it now, will change it asap.

**Pull request merged**
