### PR TITLE
Added a Roman To Integer function

### PR DESCRIPTION
**Pull request by Sudhi27Krishna**
Takes String as arguments and returns Integer .

### CODE REVIEW

**Comment by adarsh-gupta101** [comment]
Hi, this problem has been solved in the objects section [RomantoInt](https://github.com/adarsh-gupta101/DataStructures-Algorithms-in-JavaScript-TypeScript/blob/main/objects/problems/romannumber.js).

**Comment by adarsh-gupta101** [comment]
I will merge the request, since implementation is different.🚀

**Comment by Sudhi27Krishna** [comment]
> I will merge the request, since implementation is different.🚀

Thanks man! It was my first merged pull request.  Thanks for the encouragement.

**Comment by adarsh-gupta101** [comment]
Keep up the good work

**Pull request merged**
