### PR TITLE
sort array of object by property values

### PR DESCRIPTION
**Pull request by sanil011**
Add a program to sort array by property name.
Add a program to sort array by property name

### CODE REVIEW

**Comment by adarsh-gupta101** [comment]
You dont need to create a sub directory, remove the directory and only add the program files and filename should not have spaces in between

**Comment by sanil011** [comment]
> You dont need to create a sub directory, remove the directory and only add the program files and filename should not have spaces in between

done✅

**Review by adarsh-gupta101 — APPROVED** [review]
Good Job

**Comment by sanil011** [comment]
this repo is not include in hacktoberfest??

**Comment by adarsh-gupta101** [comment]
The label is added but the HTB team decides the inclusion. Does the website shows it is not accepted?

**Comment by sanil011** [comment]
now showing , but in waiting.

**Pull request merged**
